version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: "guest" 
      RABBITMQ_DEFAULT_PASS: "guest"  
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  

    networks:
      - mybridge

networks:
  mybridge:
    driver: bridge
volumes:
  rabbitmq-data: